// Generates docs/design/contrast-audit.md — a human-readable artefact listing
// every audited token pair with its WCAG 2.x contrast ratio and the action
// taken. This file is NOT the source of truth: test/contrast_test.dart is.
//
// The hex values below mirror lib/core/theme/tokens.dart (post-adjustment).
// Keep them in sync; the test guards the actual thresholds.

import 'dart:io';
import 'dart:math' as math;

const _tokens = <String, int>{
  'surface-base': 0xFFF7EE,
  'surface-raised': 0xFFFFFF,
  'ink-primary': 0x3A2E22,
  'ink-secondary': 0x7E6F62,
  'effort-track': 0xC67F17,
  'skill-track': 0x5C9C78,
  'scaffold-consonant': 0x5C9C78,
  'scaffold-dissonant': 0xDE6F4B,
  'border-hairline': 0xBA843E,
  'surface-base-dark': 0x2B241D,
  'surface-raised-dark': 0x352C23,
  'ink-primary-dark': 0xF5EBDD,
  'ink-secondary-dark': 0xC4B3A0,
  'effort-track-dark': 0xF2B85C,
  'skill-track-dark': 0x9BCBAE,
  'scaffold-consonant-dark': 0x9BCBAE,
  'scaffold-dissonant-dark': 0xEB9878,
  'border-hairline-dark': 0x826C55,
};

// original -> adjusted, for the "action" column
const _adjusted = <String, String>{
  'ink-secondary': '#8A7A6B -> #7E6F62 (darkened, hue preserved)',
  'effort-track': '#E8A33D -> #C67F17 (darkened, hue preserved)',
  'skill-track': '#7FB396 -> #5C9C78 (darkened, hue preserved)',
  'scaffold-consonant': '#7FB396 -> #5C9C78 (darkened, hue preserved)',
  'scaffold-dissonant': '#E07856 -> #DE6F4B (darkened, hue preserved)',
  'border-hairline': '#F0E3D2 -> #BA843E (darkened, hue preserved)',
  'border-hairline-dark': '#463A2E -> #826C55 (lightened, hue preserved)',
};

double _linear(double c) =>
    c <= 0.03928 ? c / 12.92 : math.pow((c + 0.055) / 1.055, 2.4).toDouble();

double _luminance(int rgb) {
  final r = _linear(((rgb >> 16) & 0xFF) / 255.0);
  final g = _linear(((rgb >> 8) & 0xFF) / 255.0);
  final b = _linear((rgb & 0xFF) / 255.0);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

double _ratio(int a, int b) {
  final la = _luminance(a);
  final lb = _luminance(b);
  return (math.max(la, lb) + 0.05) / (math.min(la, lb) + 0.05);
}

void main(List<String> args) {
  final root = args.isNotEmpty ? args.first : Directory.current.path;

  const textFg = ['ink-primary', 'ink-secondary'];
  const graphicFg = [
    'effort-track',
    'skill-track',
    'scaffold-consonant',
    'scaffold-dissonant',
    'border-hairline',
  ];

  final buf = StringBuffer()
    ..writeln('# Contrast audit')
    ..writeln()
    ..writeln(
      'Generated by `tool/gen_contrast_audit.dart`. '
      'Source of truth is `test/contrast_test.dart`.',
    )
    ..writeln()
    ..writeln('| Foreground | Background | Ratio | Threshold | Pass | Action |')
    ..writeln('|---|---|---|---|---|---|');

  void row(String fg, String bg, double threshold) {
    final r = _ratio(_tokens[fg]!, _tokens[bg]!);
    final pass = r >= threshold ? 'yes' : 'NO';
    final action = _adjusted[fg] ?? 'none';
    buf.writeln(
      '| $fg | $bg | ${r.toStringAsFixed(2)} | '
      '${threshold.toStringAsFixed(1)} | $pass | $action |',
    );
  }

  for (final bg in ['surface-base', 'surface-raised']) {
    for (final fg in textFg) {
      row(fg, bg, 4.5);
    }
  }
  for (final fg in graphicFg) {
    row(fg, 'surface-base', 3.0);
  }
  for (final bg in ['surface-base-dark', 'surface-raised-dark']) {
    for (final fg in ['ink-primary-dark', 'ink-secondary-dark']) {
      row(fg, bg, 4.5);
    }
  }
  for (final fg in [
    'effort-track-dark',
    'skill-track-dark',
    'scaffold-consonant-dark',
    'scaffold-dissonant-dark',
    'border-hairline-dark',
  ]) {
    row(fg, 'surface-base-dark', 3.0);
  }

  final out = File('$root/docs/design/contrast-audit.md');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${out.path}');
}
